<?php

declare(strict_types=1);

namespace Imadepurnamayasa\PhpInti\Ollama\Rag;

/**
 * Class Document
 *
 * Represents a document chunk or text segment in the RAG system.
 * It contains the textual content, metadata (like source, category, chunk index),
 * and optionally its associated float vector embedding generated by an embedding model.
 */
class Document
{
    /**
     * @var string The textual content of this chunk.
     */
    private string $content;

    /**
     * @var array Metadata associated with the chunk (e.g. ['source' => 'file.txt', 'index' => 1]).
     */
    private array $metadata;

    /**
     * @var array|null The vector embedding (array of floats) for this text chunk, or null if not yet computed.
     */
    private ?array $embedding;

    /**
     * Document constructor.
     *
     * @param string $content The text content.
     * @param array $metadata Key-value pairs of metadata.
     * @param array|null $embedding Optional vector embedding.
     */
    public function __construct(string $content, array $metadata = [], ?array $embedding = null)
    {
        $this->content = $content;
        $this->metadata = $metadata;
        $this->embedding = $embedding;
    }

    /**
     * Gets the textual content.
     *
     * @return string
     */
    public function getContent(): string
    {
        return $this->content;
    }

    /**
     * Gets the chunk metadata.
     *
     * @return array
     */
    public function getMetadata(): array
    {
        return $this->metadata;
    }

    /**
     * Gets the vector embedding.
     *
     * @return array|null An array of floats, or null.
     */
    public function getEmbedding(): ?array
    {
        return $this->embedding;
    }

    /**
     * Sets the vector embedding.
     *
     * @param array $embedding Array of floats.
     * @return self The document instance for method chaining.
     */
    public function setEmbedding(array $embedding): self
    {
        $this->embedding = $embedding;
        return $this;
    }
}
